package si.fri.kodiranje.gui;

import javax.swing.JFileChooser;
import si.fri.kodiranje.main.Kodiranje;

/**
 * Večji del tega razreda je Netbeans zgeneririral avtomatsko
 * (mi smo risali okno z miško, Netbeans pa je generiral kodo).
 * 
 * @author netbeans & tomaz
 */
public class KodiranjeOkno extends javax.swing.JFrame {

  /**
   * Creates new form KodiranjeOkno
   */
  public KodiranjeOkno() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    vhodTF = new javax.swing.JTextField();
    izhodTF = new javax.swing.JTextField();
    kljucTF = new javax.swing.JTextField();
    metodaCB = new javax.swing.JComboBox<>();
    smerCB = new javax.swing.JComboBox<>();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Metoda");

    jLabel2.setText("Smer");

    jLabel3.setText("Vhodna datoteka");

    jLabel4.setText("Izhodna datoteka");

    jLabel5.setText("Ključ");

    metodaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B64", "NUM", "XOR" }));

    smerCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "code", "decode" }));

    jButton1.setText("Kodiraj / Dekodiraj");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Prebrskaj...");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addGap(51, 51, 51))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(50, 50, 50)))
                .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel5)
                  .addGap(110, 110, 110)))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1)
                  .addComponent(jLabel2))
                .addGap(96, 96, 96)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(kljucTF)
              .addComponent(vhodTF)
              .addComponent(izhodTF)
              .addComponent(metodaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(smerCB, 0, 202, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(metodaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(17, 17, 17)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(smerCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(vhodTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2))
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(izhodTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(kljucTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(23, 23, 23))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Ta metoda se bo klicala, ko bo uporabnik pritisnil gumb "Kodiraj / Odkodiraj"
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String metoda = (String) metodaCB.getSelectedItem();
    String smer  = (String) smerCB.getSelectedItem();
    
    String vhod   = vhodTF.getText();
    String izhod  = izhodTF.getText();
    String kljuc  = kljucTF.getText();
    
    try {
      Kodiranje.doKodiranje(metoda, smer, vhod, izhod, kljuc);
    } catch (Exception e) {}  
  }//GEN-LAST:event_jButton1ActionPerformed

  // Ta metoda se bo klicala, ko bo uporabnik pritisnil gumb "Prebrskaj..."
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // ustvarim "okno za odpiranje datotek" ...
    JFileChooser jfc = new JFileChooser();
    // ... in ga prikažem
    if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
      // če je uporabnik pritisnil gumb "odpri", ime izbrane
      // datoteke zapišem v vpisno polje "vhodTF"
      vhodTF.setText(jfc.getSelectedFile().getPath()); 
    }
  }//GEN-LAST:event_jButton2ActionPerformed

  public static void prikaziOkno() {
    // spodnja koda ustvari okno in ga prikaže
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new KodiranjeOkno().setVisible(true);
      }
    });
  }
  


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField izhodTF;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JTextField kljucTF;
  private javax.swing.JComboBox<String> metodaCB;
  private javax.swing.JComboBox<String> smerCB;
  private javax.swing.JTextField vhodTF;
  // End of variables declaration//GEN-END:variables
}
